//package hello;
//
//import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.stereotype.Controller;
//import org.springframework.web.bind.annotation.RequestMapping;
//import org.springframework.web.bind.annotation.RequestMethod;
//import org.springframework.web.bind.annotation.GetMapping;
//import org.springframework.web.bind.annotation.PathVariable;
//import org.springframework.web.bind.annotation.ResponseBody;
//
//import entities.User;
//import repositories.UserRepository;
//
//@Controller    // This means that this class is a Controller
//@RequestMapping(path="/") // This means URL's start with /demo (after Application path)
//public class MainController {
//	@Autowired // This means to get the bean called userRepository
//	           // Which is auto-generated by Spring, we will use it to handle the data
//	private UserRepository userRepository;
//	
//	@RequestMapping(value = "/Users/{id}", method = RequestMethod.GET)
//	@ResponseBody
//	public User getUserById(@PathVariable Integer id) {
//		return this.userRepository.findOne(id);
//	}
//	
//	@GetMapping(path="/hello")
//	public @ResponseBody String index() {
//		return "hello world";
//	}
//
//	@GetMapping(path="/all")
//	public @ResponseBody Iterable<User> getAllUsers() {
//		return userRepository.findAll();
//	}
//}